name: Greet User on PR

on:
  pull_request:
    types: [opened]

jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
      - name: Greet User
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const AitSad = "Gee, Thanks!";
            const author = context.payload.pull_request.user.login;
            github.issues.createComment({
              issue_number: context.payload.pull_request.number,
              owner: 'AitSad',
              repo: context.repo.repo,
              body: `${AitSad} @${author}, welcome to this pull request!`
            });
