name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "Gee, Thanks! Your issue will definitely be considered, and once again thanks for your contribution!"
        pr-message: "Gee, Thanks for your contribution! Precious, Valuable, and will be considered if slays!"
